### ISSUE TITLE
"O nome do repositório é inválido"

### ISSUE THREAD

**Issue by LucasLBrandao** [analise-viz-dados-1sem-2020/forum-discussao#10]
Após criar o projeto no R e fazer as alterações no código, cliquei em git para realizar o commit. Entretanto me deparei com a página em branco:
![image](https://user-images.githubusercontent.com/65780588/83317066-813a4200-a200-11ea-84ef-dd9489463943.png)
e quando clico em atualizar ou em commit, a mensagem abaixo aparece
![image](https://user-images.githubusercontent.com/65780588/83317036-4506e180-a200-11ea-915d-f3a3cdf336cb.png)
mesmo após "me apresentar" para o git através dos comandos "user.name" e "user.email", o erro se manteve

**Comment by LucasLBrandao** [comment]
Fiz no Rstudio Cloud e deu certo, mas gostaria de entender o que aconteceu pois prefiro utilizar o R local

**Comment by eduardoresende** [comment]
Lucas, acho que o diretório local não pode conter palavras com acentos. Talvez seja isso. Vi um usuário com o mesmo problema nesse [fórum](https://stackoverflow.com/questions/21676188/windows-rstudio-git-directory-name-is-invalid)

**Comment by fjuniorr** [comment]
É um bom palpite. No issue #5 parece ter acontecido a mesma coisa mas em um macosx.
