### ISSUE TITLE
Alterações não foram feitas no git

### ISSUE THREAD

**Issue by Gim18** [analise-viz-dados-1sem-2020/forum-discussao#12]
Quando eu fiz o Push no Rcloud, das modificações no exercício 1 o exercício 2,  não subiu para o github? E elas não aparecem mais no Rcloud.
O que pode ter ocorrido?

**Comment by eduardoresende** [comment]
Estou um problema parecido com o R local. Dou o commit e o push e retorna como sucedido, mas não atualiza no GitHub. Percebi também que não recebi o email para colaborar dessa vez (copiei o link direto do GitHub). Talvez estamos sem permissão?
![image](https://user-images.githubusercontent.com/65866392/83969446-789fd680-a8a6-11ea-97e6-6702723147eb.png)

**Comment by vivisn** [comment]
Estou com com mesmo problema! Inclusive estou com dúvidas se minhas alterações foram, pois tive inúmeros problemas e realizei muitas ações para resolvê-los e não tive a resposta se essas ações foram sucedidas ou não.  Como conseguiria visualizar as alterações?

**Comment by fjuniorr** [comment]
A interface do Rstudio peca em não ofertar um feedback se o push foi bem sucedido ou não, mas esse tende a ser um [padrão das interfaces de linha de comando](https://wiki.c2.com/?RuleOfSilence) que em geral apenas emitem mensagem quando um erro ocorre.

Em relação ao convite para colaborar no repositório, aparentemente [algumas pessoas não receberam](https://github.com/analise-viz-dados-1sem-2020/forum-discussao/issues/6#issuecomment-639734584) o email essa semana, mas se vocês conseguem ver o repositório com o nome de vocês a permissão foi concedida. 

Essa semana os repositórios estão com a visibilidade privada, para que todos tenham a oportunidade de fazer a pesquisa, e, portanto, não é possível ver os repos dos demais alunos.

Sobre o erro de push, pela descrição não tenho nenhum palpite. Fiquem à vontade para agendar um atendimento.

**Comment by Gim18** [comment]
Soluções apresentadas.
