### ISSUE TITLE
Erro - commit

### ISSUE THREAD

**Issue by marianafortunato** [analise-viz-dados-1sem-2020/forum-discussao#13]
Professor, boa noite!

Quando tento dar o push dos arquivos retorna a seguinte mensagem:

![image](https://user-images.githubusercontent.com/65910647/85182337-c2050400-b25e-11ea-8079-3dda7ea066ac.png)

O que fazer?

Obrigada!

**Comment by fjuniorr** [comment]
@marianafortunato para conseguir realizar o push você deve clonar e utilizar o seu [repositório](https://github.com/analise-viz-dados-1sem-2020/hw01-analise-viz-dados-marianafortunato).

Todos os repositórios da organização [analise-viz-dados-master](https://github.com/analise-viz-dados-master) são apenas para fins de organização da disciplina, mas estão em modo "somente leitura".

Ps. Em cada atividade eu crio um repositório específico que deve ser utilizado para fins da mesma. Nesse caso, o repositório é o [hw01-analise-viz-dados-marianafortunato](https://github.com/analise-viz-dados-1sem-2020/hw01-analise-viz-dados-marianafortunato) e não o [hw01-introducao-programacao-marianafortunato](https://github.com/analise-viz-dados-1sem-2020/hw01-introducao-programacao-marianafortunato).

**Comment by marianafortunato** [comment]
Boa noite, professor!

Esclarecido o erro e modificado.

Muito obrigada!
