### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by kamelotti** [analise-viz-dados-1sem-2020/forum-discussao#14]
Bom dia, professor. 

Não tenho recebido nenhum retorno com relação às atividades, e embora eu sempre cheque no repositório se de fato foram feitos, não tenho tido retorno se foram feitos corretamente. Você tem dado retorno em algum caso?

**Comment by fjuniorr** [comment]
@kamelotti infelizmente não tenho conseguido oferecer feedback em cada atividade durante a entrega das mesmas. Minha expectativa é suprir essa lacuna com os [vídeos de discussão das atividades](https://www.youtube.com/watch?v=g4WGrHXs7HI&lc=UgyiGr6V_YlyDKAM1k14AaABAg).
