### ISSUE TITLE
Gráfico com "buraco"

### ISSUE THREAD

**Issue by letdufloth** [analise-viz-dados-1sem-2020/forum-discussao#15]
Na atividade do dia 10/07, ao fazer o left_join, a coluna referente à contagem acumulada dos óbitos ficava com "NA" nos dias em que não havia óbitos. Foram dois dias em que isso aconteceu, desde que começaram a ter óbitos: 04/04 e 09/04. Por causa disso, o gráfico ficou com dois "buracos", nesses respectivos dias.

O ideal seria computar os dias em que não tiveram óbitos como 0, e não como NA, pois a contagem acumulada seria a do dia anterior + 0, e não geraria problemas na visualização. Como fazer isso?

![Grafico atividade 10-07](https://user-images.githubusercontent.com/65625030/87182585-d6b34580-c2ba-11ea-86e1-090ad30bb56e.png)

**Comment by mylenadiasq** [comment]
Aconteceu o mesmo comigo! O meu gráfico ficou com esse dois "buracos" também.

**Comment by kamelotti** [comment]
Eu resolvi esse problema do NA substituindo os lugares onde ele aparecia com zero. Usei a função 
**replace(df_letal,list = is.na(df_letal), values = 0)**
 _*df_letal aqui é o data frame que eu criei juntando as ocorrências de casos e óbitos._
