### ISSUE TITLE
Left_Join retorna N/A para colunas do segundo argumento

### ISSUE THREAD

**Issue by pedro-polastri** [analise-viz-dados-1sem-2020/forum-discussao#16]
Olá Professor,
Na tentativa de executar a atividade referente ao dia 10/07 escrevi o seguinte código:
![image](https://user-images.githubusercontent.com/65868886/87185108-90acb080-c2bf-11ea-8d97-a96f77be73ea.png)

Entretanto, ao verificar a nova tabela criada com o cruzamento dos dados obtive a tabela abaixo:
![image](https://user-images.githubusercontent.com/65868886/87185156-a9b56180-c2bf-11ea-9f4e-f61f370dad8b.png)

Assim não consegui criar a variável Taxa de Mortalidade e elaborar o gráfico. Como proceder?

**Comment by pedro-polastri** [comment]
Verifiquei que as datas estão em formatos diferentes nos dois df: um deles com o formato aaaa-mm-dd e o outro com o formato dd/mm/aaaa. Isso pode ter alguma relação?

**Comment by fjuniorr** [comment]
Exatamente. No issue https://github.com/analise-viz-dados-1sem-2020/forum-discussao/issues/17#issuecomment-657279925 eu descrevi o snippet para leitura dos arquivos que corrige esse problema.

Além disso, no `count` de casos confirmados não é necessário utilizar a variável `EVOLUCAO`. Todo caso que evolui para óbito também deve ser considerado um caso confirmado.
