### ISSUE TITLE
Erro - ggsave - col data notificações de óbitos

### ISSUE THREAD

**Issue by marianafortunato** [analise-viz-dados-1sem-2020/forum-discussao#17]
Boa noite, professor!

Depois de executar todos os comandos, após o último, tem-se essa mensagem. Já alterei vários comandos no início, com o intuito de fazer a leitura por meio de um mesmo tipo, mas não resolveu. Como proceder?

![image](https://user-images.githubusercontent.com/65910647/87236718-fafa4980-c3c2-11ea-8852-fc9d50616f4f.png)

Atenciosamente,

**Comment by kamelotti** [comment]
Estou com o mesmo problema. Já tentei as formas que encontrei para alterar a leitura da coluna para Data, sem sucesso.

**Comment by fjuniorr** [comment]
@marianafortunato o problema das datas terem sido lidas com tipos incompatíveis é resolvido com a importação que estava no relatório dinâmico hw04-analise-viz-dados.Rmd

```r
library(readr)
df_casos <- readr::read_csv2("data-raw/notificacoes-covid19-mg.csv",
                  locale = locale(encoding = "latin1", decimal_mark = ",", date_format = "%d/%m/%Y"))
df_obitos <- read_csv2("data-raw/obitos-confirmados-covid19-mg.csv", 
                    locale = locale(encoding = "UTF-8", decimal_mark = ","))
```

Note que as datas estão armazenadas com formatos diferentes nos arquivos csv.
