### ISSUE TITLE
Erro ao abrir atividade hw05

### ISSUE THREAD

**Issue by julia-tavares** [analise-viz-dados-1sem-2020/forum-discussao#18]
Não consegui abrir a atividade dessa semana (hw05-analise-viz-dados-<user>). 
Quando tento dá a seguinte mensagem de erro, no print: 

![image](https://user-images.githubusercontent.com/65626821/87429429-24c99100-c5ba-11ea-8f26-a5c92a0a6f3f.png)

**Comment by fjuniorr** [comment]
@julia-tavares eu criei o repositório com um arquivo `xlsx` que excedia o tamanho máximo permitido para o meu caso de uso.

Fiz a adequação e criação dos novos repositórios.

Obrigado pelo feedback!
