### ISSUE TITLE
Data de entrega das atividades

### ISSUE THREAD

**Issue by amasilis** [analise-viz-dados-1sem-2020/forum-discussao#19]
Professor, boa tarde! Gostaria de saber se as atividades semanais entregues fora do prazo ainda serão pontuadas, especialmente essas últimas, já que são muitos pontos distribuídos em cada uma.

Também queria saber se o senhora continuará postando as resoluções dos exercícios, pois estavam sendo de grande serventia para conferir as atividades.

**Comment by fjuniorr** [comment]
@amasilis as entregas fora do prazo serão pontuadas mas com penalização por atraso. A regra de penalização ainda precisa ser definida.
