### ISSUE TITLE
Atividade - Pesquisa Reproduzível - Controle de Versão - Compartilhamento de Análise de dados

### ISSUE THREAD

**Issue by fjuniorr** [analise-viz-dados-1sem-2020/forum-discussao#2]

**Comment by elisasanches94** [comment]
https://github.com/elisasanches94/hello-world

**Comment by Isabelle-Fernandes** [comment]
https://www.scielo.br/scielo.php?pid=S0102-311X2019000805001&script=sci_arttext

**Comment by Isabelle-Fernandes** [comment]
https://github.com/Isabelle-Fernandes/hello-world

**Comment by anamendesr** [comment]
https://github.com/ana-mendesr/hello-world

**Comment by Mateus-Espeschit** [comment]
https://github.com/Mateus-Espeschit/hello-world

**Comment by letdufloth** [comment]
https://github.com/letdufloth/hello-world

**Comment by brunovolp** [comment]
https://github.com/brunovolp/hello-world/

**Comment by vivisn** [comment]
https://github.com/vivisn/hello-world

**Comment by rodrigobp998** [comment]
https://github.com/rodrigobp998/hello-world

**Comment by barbaraoliveira-hub** [comment]
https://github.com/barbaraoliveira-hub/hello-word

**Comment by Leandro-Sepe** [comment]
https://github.com/Leandro-Sepe/hello-world

**Comment by gabisilvap** [comment]
https://github.com/gabisilvap/hello-world/blob/master/README.md

**Comment by gabisilvap** [comment]
https://github.com/gabisilvap/hello-world

**Comment by lucasshirata** [comment]
https://github.com/lucasshirata/hello-world

**Comment by natalia-toledo** [comment]
https://github.com/natalia-toledo/hello-world

**Comment by Raquel729** [comment]
https://github.com/Raquel729/hello-world

**Comment by lamagesty** [comment]
https://github.com/lamagesty/hello-world

**Comment by kamelotti** [comment]
https://github.com/kamelotti/hello-world/blob/master/README.md

**Comment by kamelotti** [comment]
https://github.com/kamelotti/hello-world

**Comment by amandasalvador** [comment]
https://github.com/amandasalvador/hello-world/blob/master/README.md

**Comment by LucasLBrandao** [comment]
https://github.com/LucasLBrandao/hello-world

**Comment by lguilhermebh** [comment]
https://github.com/lguilhermebh/hello-world/blob/master/README.md

**Comment by Melissadq** [comment]
https://github.com/Melissadq/hello-world

**Comment by mylenadiasq** [comment]
https://github.com/mylenadiasq/hello-world

**Comment by matheuscastro112** [comment]
https://github.com/matheuscastro112/hello-world

**Comment by Rayssa-Campos** [comment]
https://github.com/Rayssa-Campos/hello-world/

**Comment by julia-tavares** [comment]
https://github.com/julia-tavares/hello-world

**Comment by mariodemetrio** [comment]
https://github.com/mariodemetrio/hello-world

**Comment by kamillajota** [comment]
https://github.com/kamillajota/hello-world

**Comment by amasilis** [comment]
https://github.com/amasilis/hello-world

**Comment by pedro-polastri** [comment]
https://github.com/pedro-polastri/hello-world

**Comment by eduardoresende** [comment]
https://github.com/eduardoresende/hello-world

**Comment by Gim18** [comment]
https://github.com/Gim18/hello-world/blob/master/README.md

**Comment by cesaraca** [comment]
https://github.com/cesaraca/hello-world

**Comment by marianafortunato** [comment]
https://github.com/marianafortunato/hello-world
