### ISSUE TITLE
Função cut não recebe primeiro argumento

### ISSUE THREAD

**Issue by pedro-polastri** [analise-viz-dados-1sem-2020/forum-discussao#20]
Quando tentei executar o agrupamento da faixa etaria utilizando a função cut com o seguinte código:
![image](https://user-images.githubusercontent.com/65868886/88426017-c9bc4900-cdc6-11ea-8e12-d0b31b6690c3.png)

O console me retorna a seguinte mensagem de erro:
![image](https://user-images.githubusercontent.com/65868886/88426061-dd67af80-cdc6-11ea-9543-f123eb0e1cc2.png)

**Comment by fjuniorr** [comment]
@pedro-polastri fiz a explicação abaixo para outro aluno, apesar dos nomes diferentes, é o mesmo caso. Veja se soluciona sua dúvida.

> O problema está ocorrendo pelo seguinte (limpei um pouco o código pra focar no essencial)
> 
> ```r
> df_obitos %>% 
>   cut(IDADE,
>       c(0,5,15,20,25,30,35,40,45,50,55,60,65,70,75), 
>       labels = c("0a4","5a9","10a14","15a19","20a24","25a29","30a34","35a39","40a49","50a54","55a59","60a64","65a69","70a74","75a79","80+"),
>       include.lowest = TRUE, 
>       right = FALSE)
> ```
> 
> Esse código passa como primeiro argumento para a função `cut` o `df_obitos`, que é um data.frame. No entanto, ela espera um vetor, explicando a mensagem de erro
> 
> ```
> Error in cut.default(., IDADE, c(0, 5, 15, 20, 25, 30, 35, 40, 45, 50,  : 
>   'x' must be numeric
> ```
> 
> `x` no caso é o primeiro argumento de cut. Lembrando que sem o pipe a chamada seria
> 
> ```r
> cut(df_obitos, IDADE,
>       c(0,5,15,20,25,30,35,40,45,50,55,60,65,70,75), 
>       labels = c("0a4","5a9","10a14","15a19","20a24","25a29","30a34","35a39","40a49","50a54","55a59","60a64","65a69","70a74","75a79","80+"),
>       include.lowest = TRUE, 
>       right = FALSE)
> ```
> 
> Um modo correto de executar o cut de forma independente é
> 
> ```r
> cut(df_obitos$IDADE,
>       c(0,5,15,20,25,30,35,40,45,50,55,60,65,70,75), 
>       labels = c("0a4","5a9","10a14","15a19","20a24","25a29","30a34","35a39","40a49","50a54","55a59","60a64","65a69","70a74","75a79","80+"),
>       include.lowest = TRUE, 
>       right = FALSE)
> ```
> 
> Mas no nosso caso, como queremos inserir isso como uma nova coluna, podemos colocar tudo dentro de um mutate:
> 
> ```r
> df_obitos %>% 
>   mutate(FAIXA_ETARIA = cut(IDADE,
>       c(0,5,15,20,25,30,35,40,45,50,55,60,65,70,75), 
>       labels = c("0a4","5a9","10a14","15a19","20a24","25a29","30a34","35a39","40a49","50a54","55a59","60a64","65a69","70a74","75a79","80+"),
>       include.lowest = TRUE, 
>       right = FALSE))
> ```
> 
> Esse último snippet ainda gera uma mensagem de erro, mas é um ajuste que você precisa fazer entre o número de breaks e os labels.

**Comment by fjuniorr** [comment]
@pedro-polastri vou considerar essa questão como solucionada. Pode reabrir o issue se ainda restou dúvidas.
