### ISSUE TITLE
Gráfico não aparece no documento ao dar knit

### ISSUE THREAD

**Issue by letdufloth** [analise-viz-dados-1sem-2020/forum-discussao#21]
Boa noite!

Ao fazer o trabalho final no R markdown, queria ocultar o código e exibir o resultado (gráfico), o que, segundo os slides, poderia ser resolvido com a chunk option "echo = FALSE". Contudo, ao dar knit, só aparece isso onde deveria aparecer o gráfico:

![Problema knit](https://user-images.githubusercontent.com/65625030/88603514-8aeaf500-d04b-11ea-8cb0-7d51f54556e8.png)

Os gráficos estão salvos em pdf. Tentei salvar em jpeg pra ver se resolveria o problema, mas não deu certo. Como posso resolver esse problema?

**Comment by fjuniorr** [comment]
@letdufloth faz o commit do estágio atual do código que eu dou uma olhada. 

Executando os scripts do `.Rmd` [atual](https://github.com/analise-viz-dados-1sem-2020/hw99-analise-viz-dados-grupo09/blob/3f346a5806dfce13884b00490c1adede9dbd974b/trabalho_final.Rmd) os data frames gerados estão vazios.

**Comment by letdufloth** [comment]
Professor, acabei de fazer o commit, estava mexendo na minha parte.

Eu meio que descobri onde está o erro: eu fiz alguns gráficos usando a função barplot(), do R base. Esses não aparecem, mas os gráficos que fiz usando o ggplot() aparecem. Você sabe como resolver isso? Porque fiz vários gráficos com o barplot()

**Comment by fjuniorr** [comment]
@letdufloth algumas observações. As recodificações 

```r
df$Sexo[(df$Sexo)=="M"] <- "Masculino"
df$Sexo[(df$Sexo)=="F"] <- "Feminino"

df$Deficiente_Fisico[(df$Deficiente_Fisico)=="S"] <- "Sim"
df$Deficiente_Fisico[(df$Deficiente_Fisico)=="N"] <- "Nao"
```

estão inserindo valores ausentes em todas as linhas para as variáveis `Sexo` e `Deficiente_Fisico` e isso faz com que a função `na.omit` retorne data frames com zero observações (tendo em vista que toda linha tem pelo menos um NA).

Para fazer recodificação de fatores uma opção é usar a função `fct_recode` do pacote `forcats`.

Em relação aos gráficos, ao invés de 

```r
pdf("figures/faixaetaria.pdf", width = 11, height = 10)
barplot(freq.fxet, main = "Número de beneficiários por faixa etária", col = "brown3", ylim = c(0, 99000))
dev.off()
```

use

```r
barplot(freq.fxet, main = "Número de beneficiários por faixa etária", col = "brown3", ylim = c(0, 99000))
```

**Comment by letdufloth** [comment]
Obrigada, professor! Fiz as alterações.
