### ISSUE TITLE
Dúvida sobre left_join 

### ISSUE THREAD

**Issue by julia-tavares** [analise-viz-dados-1sem-2020/forum-discussao#23]
Boa tarde, professor!
Estou tentando usar a função left_join no trabalho final para juntar os dados que tenho do número de bolsas ofertadas do prouni em 2019 por UF com outra base que tem a população de cada uma delas para esse ano para poder calcular e analisar a distribuição relativa das bolsas, uma vez que as discrepâncias entre os números absolutos podem ser devido às diferenças de população. Porém, quando tento, a coluna de população na tabela final aparece apenas com NAs, ao invés das populações observadas na tabela original. Não sei o que estou fazendo errado. Veja os prints para ver se consegue me ajudar.

**Tabela Bolsas/UF:**
![image](https://user-images.githubusercontent.com/65626821/88853399-0e305600-d1c6-11ea-9c07-b08c749662a4.png)

**Tabela População/UF:**
![image](https://user-images.githubusercontent.com/65626821/88853472-2607da00-d1c6-11ea-935d-8d91c5ad57af.png)

**Função utilizada:
ufs_pop <- left_join(ufs, pop, by="UF")**

**Resultado quando executo:**
![image](https://user-images.githubusercontent.com/65626821/88853569-4d5ea700-d1c6-11ea-9512-4e997c9e21fc.png)

**Comment by fjuniorr** [comment]
@julia-tavares pelos prints não tenho nenhum palpite. 

Você consegue fazer um commit intermediário com o status atual para que eu avalie o código?

**Comment by julia-tavares** [comment]
Sim. Acabei de fazer o commit 690cf0955172ff033847d336bfdbaad1325edce0 no [repositório](https://github.com/analise-viz-dados-1sem-2020/hw99-analise-viz-dados-grupo09). A tentativa de inclusão dos dados da população começa na linha 272 do Rmd.

**Comment by fjuniorr** [comment]
O problema era o espaço vazio no início da coluna. 

``` r
library(magrittr)

x <- c(" RO", " AC", " AM", " RR", " PA", " AP", " TO", " MA", 
       " PI", " CE", " RN", " PB", " PE", " AL", " SE", " BA", 
       " MG", " ES", " RJ", " SP", " PR", " SC", " RS", " MS", 
       " MT", " GO", " DF") # valores correspondem a ufs_pop$UF
  
y <- c("AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", 
       "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", 
       "RR", "RS", "SC", "SE", "SP", "TO") # valores correspondem a ufs$UF

match(x, y) %>% 
  anyNA() # algum estado não possui correspondência?
#> [1] TRUE

trimws(x, whitespace = "[\\h\\v]")
#>  [1] "RO" "AC" "AM" "RR" "PA" "AP" "TO" "MA" "PI" "CE" "RN" "PB" "PE" "AL" "SE"
#> [16] "BA" "MG" "ES" "RJ" "SP" "PR" "SC" "RS" "MS" "MT" "GO" "DF"

trimws(x, whitespace = "[\\h\\v]") %>% 
  match(y) %>% 
  anyNA() # algum estado não possui correspondência?
#> [1] FALSE
```

A solução é você usar a função `trimws` dentro de um mutate.

**Comment by julia-tavares** [comment]
Obrigada, professor!
