### ISSUE TITLE
Sem opções na aba git para commit

### ISSUE THREAD

**Issue by Leandro-Sepe** [analise-viz-dados-1sem-2020/forum-discussao#5]
Boa tarde professor,
Eu estou fazendo o uso do RStudio local, instalei todos aqueles programas, consegui puxar o repositório do github, alterar o arquivo e rodar. A figura ficou certa, usando o meu nome e tudo mais. Mas na hora de salvar e fazer o commit pra salvar lá no github não aparece nenhuma opção para eu marcar, aí não faz o commit de arquivo nenhum. Alguma ideia de qual o problema?
Tirei um print, vou tentar anexar aqui.

![Captura de Tela 2020-05-27 às 16 12 11](https://user-images.githubusercontent.com/65780510/83062588-4c2dc400-a035-11ea-874a-b61956ab026e.png)

**Comment by fjuniorr** [comment]
Ainda não tenho um palpite! :thinking:

Clica na aba `Terminal`, do lado de `Console`, executa os comandos

```sh
git status
git remote --v
```

e manda o resultado aqui.

**Comment by Leandro-Sepe** [comment]
![Captura de Tela 2020-05-27 às 22 26 56](https://user-images.githubusercontent.com/65780510/83088140-4fdb3e00-a069-11ea-81f9-17ef171a4141.png)

**Comment by Leandro-Sepe** [comment]
Consegui lá professor, mas ao invés de selecionar os arquivos na aba 'git' eu fui no terminal e escrevi "git add figures/nomes-decada.pdf" e dps "git add hw-rstudio-project.R". Aí eles ficaram como se estivessem selecionados, aí fiz o commit e o push e apareceu la no github a mudança.

Mas assim, não é nem um pouco prático fazer isso toda vez pra todo arquivo q eu modificar. Será que tem como arrumar esse problema?

**Comment by fjuniorr** [comment]
Marca um horário que a gente investiga!

**Comment by fjuniorr** [comment]
Nesse caso o problema era o uso de [caractere especial](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) `/` no nome das pastas:

![image](https://user-images.githubusercontent.com/4969445/83300706-da897d80-a1ce-11ea-8bbe-578f8212dc02.png)

Problema encontrado [nessa discussão](https://community.rstudio.com/t/odd-rstudio-git-issue-git-tab-present-but-empty-even-when-changed-files-present/50969).
