### ISSUE TITLE
Atendimento para dúvidas

### ISSUE THREAD

**Issue by fjuniorr** [analise-viz-dados-1sem-2020/forum-discussao#6]
Será ofertado atendimento síncrono no horário usual da aula (Sexta feira 13:00 às 14:40) para solução de dúvidas. 

O atendimento será no [Jitsi Meet](https://meet.jit.si/CSAP2020-R) da disciplina, mediante agendamento prévio realizado [neste link](https://meetings.hubspot.com/fjunior-alves-oliveira).

__Se o atendimento não for mais necessário, cancele o compromisso no seu calendário.__

**Comment by Rayssa-Campos** [comment]
Boa tarde, Francisco!
Você já disponibilizou o convite para colaboração no repositório da aula de hoje (05/06)? Se sim, você poderia me auxiliar onde encontro?

**Comment by gabisilvap** [comment]
Boa tarde, professor!
Estou com o mesmo problema da Rayssa, não consegui encontrar o convite de colaboração no repositório.

**Comment by fjuniorr** [comment]
Era pra ter iso. Vou verificar agora o que ocorreu!

**Comment by fjuniorr** [comment]
Gente, vcs duas estão com acesso aos repositórios:

* <https://github.com/analise-viz-dados-1sem-2020/hw01-introducao-programacao-Rayssa-Campos>
![image](https://user-images.githubusercontent.com/4969445/83914609-ec779d00-a747-11ea-9244-d50b31b7c08c.png)

* <https://github.com/analise-viz-dados-1sem-2020/hw01-introducao-programacao-gabisilvap>
![image](https://user-images.githubusercontent.com/4969445/83914625-f7323200-a747-11ea-8a89-a4bb224ca210.png)

O que acontece quando vocês tentam entrar no link acima do repositório de vcs?
