### ISSUE TITLE
Erro "there is no package 'httr'"

### ISSUE THREAD

**Issue by barbaraoliveira-hub** [analise-viz-dados-1sem-2020/forum-discussao#7]
Ao executar a alteração de nomes, meu script resultava em um erro de execução com a seguinte mensagem "there is no package 'httr'". Caso alguém tenha o mesmo problema, consegui executar após clicar em Files-> Pasta R-> Utils.R. Ao executar esse último script, ocorre um erro por falta de instalação de alguns pacotes. Assim, é necessário baixar os pacotes descritos e a execução da atividade pode ser feita.

**Comment by amandasalvador** [comment]
O meu aconteceu o mesmo! Selecionei a opção de instalar o pacote e pareceu que tinha resolvido. Entretanto, quando cliquei no GIT para fazer o commit não tinha nenhum arquivo para selecionar. 
Aconteceu com alguém?

**Comment by fjuniorr** [comment]
Esse vai ser um problema recorrente até que eu [encontre uma solução definitiva](https://community.rstudio.com/t/new-project-from-git-repo-installed-packages-not-inherited-from-base-project/68057). 

## Solução provisória

Os quatro pacotes que estamos utilizando nesta atividade são: magrittr, ggplot2, httr, dplyr. Para instalá-los, execute o comando abaixo. Você pode adicionar ao seu script no editor de texto e executar a partir de lá (ctrl+enter) ou executar diretamente no console.

```
install.packages(c("magrittr", "ggplot2", "httr", "dplyr"))
```

## Contexto

Isso é pra quem tiver curiosidade e quer entender melhor a natureza do problema.  

O ambiente que eu preparei para as nossas atividades está configurado para já dispor dos pacotes que vamos utilizar. Ou seja, quando iniciamos um projeto no ambiente "Análise E Visualização de Dados com R - 2020/01" este projeto já conta com diversos pacotes instalados. 

Quando criamos um projeto a partir de um repositório no GitHub, nos é dada a opção 
*"Add packages from the base project"*. Quando abrimos o botão de informação ele nos relembra que o ambiente possui um *projeto base* e que os pacotes deste *projeto base* podem ser adicionados ao projeto que será criado a partir do repositório Git.

![image](https://user-images.githubusercontent.com/4969445/83310790-a1a7d380-a1e3-11ea-8d7b-1f7c9ccf191b.png)

Em condições normais, portanto, ao selecionarmos a opção *"Add packages from the base project"* os pacotes necessários para execução da atividade já estariam instalados. Porém, como vocês perceberam, não é o que está acontecendo. 

[Estou buscando auxílio para solução desse problema](https://community.rstudio.com/t/new-project-from-git-repo-installed-packages-not-inherited-from-base-project/68057). Enquanto isso, fiquem atentos à instrução acima nessa e nas próximas atividades.

**Comment by marianafortunato** [comment]
Professor, boa noite! Mesmo com esse comando não teve mudança no meu Como proceder?

**Comment by fjuniorr** [comment]
Ei Mariana. Coloque um print screen com o erro para possibilitar a avaliação do que pode ter ocorrido.

**Comment by marianafortunato** [comment]
Ei, professor! Seguem, abaixo, os prints após a execução do comando:

![image](https://user-images.githubusercontent.com/65910647/83333754-9652b780-a278-11ea-8476-eaef11a90920.png)

![image](https://user-images.githubusercontent.com/65910647/83333771-aa96b480-a278-11ea-8937-ebe1342cec4a.png)

Obrigada!

**Comment by amandasalvador** [comment]
Aqui também não resolveu. A aba git continua vazia 
![image](https://user-images.githubusercontent.com/65791466/83361477-abeedc80-a35f-11ea-9847-0061f199594a.png)

**Comment by fjuniorr** [comment]
Na [primeira videoaula](https://youtu.be/KMeqjCJQTbI) do dia 05/06 eu discuti esse problema.

Acho que ele vai solucionar todas as dúvidas. 

 Fiquem à vontade para reabrir o issue caso necessário.

**Comment by fjuniorr** [comment]
Recebi a [dica de uma alternativa](https://community.rstudio.com/t/new-project-from-git-repo-installed-packages-not-inherited-from-base-project/68057/4?u=fjunior) para contornar esse problema e fiz o procedimento.

No entanto ele somente será aplicado para novos projetos.
