### ISSUE TITLE
Erro - instalação local

### ISSUE THREAD

**Issue by Rayssa-Campos** [analise-viz-dados-1sem-2020/forum-discussao#8]
Olá pessoal.
Não estou conseguindo abrir um novo projeto utilizando o RStudio instalado no meu computador. Aparece a msg:

"Git wad not detected on the system path"
Alguém está com o mesmo problema?

**Comment by LucasLBrandao** [comment]
Rayssa, acho que você tem que instalar o programa "Git", nesse [link](https://git-scm.com/) disponibilizado pelo professor você consegue. A mensagem acusou que não encontrou o programa no seu computador

**Comment by mariodemetrio** [comment]
Tive o mesmo problema e estou com o Git instalado...

**Comment by fjuniorr** [comment]
Pela mensagem, o git pode até estar instalado, mas o local de instalação não foi adicionado a variável de ambiente `PATH`.

Eu não tenho acesso a um windows agora para testar, mas de acordo com as [instruções que eu havia passado](https://happygitwithr.com/install-git.html#install-git-windows),  acho que nesse momento da instalação vocês escolheram a primeira opção

![image](https://user-images.githubusercontent.com/4969445/83444247-80342b00-a421-11ea-8ca9-4e419bb862e7.png)

Ainda é possível fazer essa configuração. Se não encontrarem um tutorial com a busca "how to add git to PATH in windows" marquem um horário para atendimento que fazemos o procedimento juntos.
